nelmio_api_doc:
  documentation:
    info:
      title: Order product API
      description: This app provides simple API for orders
      version: 1.0.0
    paths:
      /api/v1/orders:
        get:
          operationId: ListOrders
          summary: Search all orders
          description: Search orders
          tags:
            - Orders
          responses:
            '200':
              description: Successful operation
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: '#/components/schemas/OrderResponse'
            '400':
              description: Bad request
            '422':
              description: Validation errors
        post:
          operationId: CreateOrder
          summary: Create order
          description: Create order by request
          tags:
            - Orders
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OrderDTO'
          responses:
            '201':
              description: Successful operation
            '400':
              description: Bad request
            '422':
              description: Validation errors
      /api/v1/orders/{id}:
        get:
          operationId: GetOrder
          summary: Get order by id
          description: Get order by id
          tags:
            - Orders
          responses:
            '200':
              description: successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/OrderResponse'
            '400':
              description: Bad request
        put:
          operationId: UpdateOrder
          summary: Update order
          description: Update order by request
          tags:
            - Orders
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OrderDTO'
          responses:
            '200':
              description: Successful operation
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/OrderResponse'
            '400':
              description: Bad request
            '404':
              description: Order not found
            '422':
              description: Validation errors
        delete:
          operationId: DeleteOrder
          summary: Delete order
          description: Delete order
          tags:
            - Orders
          responses:
            '204':
              description: Successful operation
            '404':
              description: Order not found
    components:
      schemas:
        OrderResponse:
          properties:
            id:
              type: integer
              example: 1
            currency:
              type: string
              example: GBP
            date:
              type: string
              format: date
              example: 12/12/2022
            total:
              type: integer
              format: int64
              example: 1000
            products:
              type: array
              items:
                $ref: '#/components/schemas/OrderProductDTO'
        OrderDTO:
          type: object
          properties:
            currency:
              type: string
              example: GBP
            date:
              type: string
              format: date
              example: 12/12/2022
            total:
              type: integer
              format: int64
              example: 1000
            products:
              type: array
              items:
                $ref: '#/components/schemas/OrderProductDTO'
        OrderProductDTO:
          type: object
          properties:
            product:
              type: string
              example: Product name
            price:
              type: integer
              format: int64
              example: 1000
  areas: # to filter documented areas
    disable_default_routes: true
    path_patterns:
      - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
